### PR TITLE
added YAML DeepMerge CMDB - fixes RexOps/Rex#499

### PR DESCRIPTION
**Pull request by krimdomu**
This adds a DeepMerge YAML CMDB.

To load it:

```perl
set cmdb => {
  type => 'Rex::CMDB::YAML::DeepMerge',
};
``` 

To set merge behavior:
```perl
set cmdb => {
  type => 'Rex::CMDB::YAML::DeepMerge',
  merge_behavior => 'SOME-TYPE',
};
```

The merge is done with Hash::Merge (https://metacpan.org/pod/Hash::Merge) so the behavior can also be customized.

### CODE REVIEW

**Comment by ferki** [comment]
@krimdomu: would you consider specifying the current behaviour as a custom Hash::Merge behaviour and use that by default (to provide backwards compatibility), instead of splitting the YAML module into a Default and a DeepMerge variant? I think it can be done with `specify_behaviour` of Hash::Merge.

Or am I missing some reason to keep them separate? :)

**Comment by krimdomu** [comment]
well the only reason is, that with the separation there is no possibility to break the old code :)

**Comment by ferki** [comment]
Well, in my opinion that's why we have tests for the current behaviour, so we can be sure that we don't break compatibility either way ;)

If I'm not mistaken the current behaviour is to "always keep the left value" (=the first value found), right? That sounds simple enough to describe and use as default merge behaviour, and also easy to override if `merge_behaviour` is passed.

If you're willing to merge it this way, I'm willing to code it :) I'd like to do this because I believe this would simplify long-term maintenance.

ps.: we also can probably easily support passing a hashref to `merge_behaviour`, and calling `specify_behaviour` in this case, allowing users to describe arbitrary merging rules on top of the builtin ones.

**Comment by krimdomu** [comment]
@ferki sure, we can merge both modules into one. but then we should default to "no merge". So that the current behaviour doesn't change.

**Comment by ferki** [comment]
@krimdomu: of course, maybe above I left out the bit that the default should/would be the current behaviour (first value found wins) ^^

**Comment by ferki** [comment]
see also #632

**Comment by ferki** [comment]
fixed with #632

**Pull request closed without merging**
