### PR TITLE
Libvirt: vm destroy must not die() for not-running VMs

### PR DESCRIPTION
**Pull request by alip**

### CODE REVIEW

**Comment by Tweaki** [comment]
Can one of the admins verify this patch?

**Comment by alip** [comment]
> verify this patch?

What does that even mean?

**Comment by krimdomu** [comment]
Hi @alip ,

thanks for this patch. This is a jenkins/github bot where we can control the merge and testing process.

**Comment by alip** [comment]
@krimdomu: Thank you. For a moment I pictured the bot as a human who needed the patch badly. :)

**Comment by alip** [comment]
There are a couple of other improvements for Libvirt.pm, I hope I'll have the time soon to come up with more patches (ping alip on freenode if you are motivated to do them yourself, I can give you a quick summary, nothing complicated really, simple useful improvements and possibly ideas to push some to libvirt as these are not necessarily rex issues)

**Pull request merged**
