### PR TITLE
Feature firewall

### PR DESCRIPTION
**Pull request by krimdomu**
This pr adds the Firewall module from rex-recipes to core.

This is the first module which will use the `resource` syntax which will automatically add `on_change` options and reporting.

this pr has a dependency to #804

### CODE REVIEW

**Comment by krimdomu** [comment]
well, it doesn't have a dependency, it includes it.. *grml*
i'm going to cherry-pick this at the end

**Comment by ferki** [comment]
Nice! :+1:

If I understand correctly, it requires ParamLookup, so that needs to be merged first (#804) I guess after that, we can rebase/rework this branch easily to have a clean test-merge cycle here too.

**Comment by krimdomu** [comment]
@ferki right

**Comment by abeverley** [comment]
Awesome, thanks very much!

**Pull request merged**
