### PR TITLE
feature for treating hostnames starting with sequential numbers

### PR DESCRIPTION
**Pull request by okaoka**
prefix "^" enables you to treat hostnames starting with sequential numbers like the following .
```
[cassandra]
^[01..02]-cassandra
```

### CODE REVIEW

**Comment by ferki** [comment]
@okaoka: nice, thanks for this patch!

Do you think we can use a slightly different method to recognize the leading numbers (and avoid using `^` as a special marker)? I'm thinking about something like:
- if the entry matches `m{^\[\d+(?:\.\.|,)\d+(?:/\d+)\]}` treat it as host

**Comment by okaoka** [comment]
@ferki
I tried not to use special marker .

**Comment by ferki** [comment]
@okaoka: If I understand correctly it would recognize entries like `[01..02]-cassandra` ("one or more digits, followed by optional `..`, followed by one or more digits, all within square brackets").

I think rex should also handle the following cases (those are supported by e.g. the `-H` CLI option, and recognized as host specification):
- `[01,02]-cassandra` (comma separated)
- `[01..05/2]-cassandra` (range operator with a stepping)

ps.: the full [list of supported expressions](http://www.rexify.org/api/Rex/Commands.pm.html#group-name-servers-) can be found in the docs, but the above should be all of them currently

**Comment by okaoka** [comment]
@ferki
Sorry for my oversight.
I fixed regular expression for treating missing expressions.

**Comment by ferki** [comment]
@okaoka: no problem, thanks for the update! And sorry for the bit late feedback too.. I expect to be able to review/merge it soon for the next release.

**Comment by ferki** [comment]
@okaoka: this is now merged, thank you! I squashed your commits together before merging, added some documentation updates about the chenges, and I also added you to the list of contributors.

**Pull request closed without merging**
