### PR TITLE
convert rexify.org/docs/guides/feature_flags.html to POD

### LINKED ISSUE #1346: Document feature flags
## User story

**As** a maintainer,
**I would like to** include the documentation of feature flags in the main codebase,
**so I can** make them more discoverable, and the distribution more self-contained.

## Describe the solution you'd like

Currently the [feature flags](https://www.rexify.org/docs/guides/feature_flags.html) are documented only on the website, which makes them harder to discover by relying on external documentation. Including this important bit of information in the main codebase (perhaps directly in the Rex module?) would make the distribution more self-contained.

The web page could either link to the main docs, or be generated directly from the POD docs.

## Describe alternatives you've considered

The authoritative source of this information is either included in the codebase or external to it. Internal feels mandatory, and external feels more optional, so at this point I'm not sure there are any real alternatives.

## Additional context

It might be a good addition to formalize and link to some kind of deprecation policy as well, since feature flags are a related concept.

### PR DESCRIPTION
**Pull request by randyl**
This PR fixes #1346  by creating a new file, lib/Rex/FeatureFlags.pod, that contains the feature-flag documentation from the website converted to POD.

Note that I moved the "How to enable Feature Flags" section above the list of feature flags, so that users don't have to scroll through a long list of flags to see example code.

Also, this PR does not address what to do with the feature-flag page on the website, but there is a separate ticket for that at https://github.com/RexOps/rexify-website/issues/119.

## Checklist

- [x] based on top of latest source code 
- [x] changelog entry included 
- [x] tests pass on Travis CI 
- [x] git history is clean    
- [x] git commit messages are [well-written](https://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Comment by randyl** [comment]
@ferki, Thanks for the feedback.

> Could you update the PR like that, please? We can also continue to work on it together as soon as I'm back online properly.

Yes, I will make those changes.

> ps.: one of the commit messages seems to have a typo ("Documenation"), and I'd say the changelog entry could by in the same commit where the change is being made, so I think the commits could be squashed together.

Good catch! Will do.

**Comment by randyl** [comment]
I've made the requested changes, but I'm not sure that my squashing of commits produced the desired effect. Perhaps you could take a look and let me know if anything else needs to be done.

**Comment by ferki** [comment]
@randyl: thanks for the PR update!

I'll give the text a thorough read before merging, and I'll try to take care of any typos or stylistic changes I might notice while review. And don't worry, I'll also handle any further squashing if needed.

**Comment by ferki** [comment]
Hmm, it looks like somehow it ended up being a mix of the original and the current version :upside_down_face: It seems like the intro text was modified to use the original version, but the examples and the flag descriptions remained on the current version.

I'll try to clean that up, but I might end up converting the original page from scratch. We'll see :)

**Comment by randyl** [comment]
Oh, I didn't realize the flag descriptions/examples had changed as well; I thought it was just the intro text. My bad. Sorry if this winds up not being very helpful.

**Comment by ferki** [comment]
> Oh, I didn't realize the flag descriptions/examples had changed as well; I thought it was just the intro text. My bad. Sorry if this winds up not being very helpful.

No worries, it _is_ helpful! I have to do more proofreading than I expected, so I wondered if it would be faster if I convert the text again instead.

Either way, I'll come up with something. And since GitHub allows me to work directly on this branch, I might tinker with it right here.

**Comment by ferki** [comment]
Looks like this PR was messed up somehow, I'll open a new one.

**Pull request closed without merging**
