### PR TITLE
Git scm improvements

### PR DESCRIPTION
**Pull request by jwbargsten**
Various little improvements to improve git handling in Rex

### CODE REVIEW

**Comment by ferki** [comment]
@jwbargsten: thanks for the PR, and sorry for the delay. I have marked them to be OK to merge for the next minor release (1.7.0), even though I believe perltidy would complain about the layout. Feel free to update the PR with reformatting if you want, but I can also do that upon merging.

**Comment by jwbargsten** [comment]
I ran it through perltidy.

**Comment by ferki** [comment]
Thanks, I will change its target branch to `master` and see if I need ot resolve any merge conflicts.

**Comment by krimdomu** [comment]
Hi @jwbargsten 
thanks for the PR and sorry for the late replay. This is now merged into master branch and is going to be in the next release.

**Pull request closed without merging**
