### PR TITLE
Fail if requested environment is not found

### PR DESCRIPTION
**Pull request by ferki**
@krimdomu: it should work™, but most probably can be done more optimally

### CODE REVIEW

**Comment by ferki** [comment]
I think I'll give it a go to find a more sophisticated solution for this. The first attempt feels more like a hack.

**Comment by ferki** [comment]
Okay, after taking a second look at the possibilities, I think we only can move around the second commit's detection logic to different parts, but I haven't found any reasonably better way to do it.

**Comment by krimdomu** [comment]
It would be nice if we could have some automated Rex::Box tests. I have to test if we can install virtualbox on build.rexify.org without affecting kvm.

**Comment by ferki** [comment]
@krimdomu: `Rex::Box` works with KVM ;)

**Comment by krimdomu** [comment]
@ferki  yes but we should also test virtualbox  and amazon and possibly other providers for Rex::Box :)

**Pull request merged**
