### PR TITLE
Fix for  #1051 - Logger.pm - uninitialized value

### PR DESCRIPTION
**Pull request by stiron**

### CODE REVIEW

**Comment by ferki** [comment]
There seems to be a [test failure](https://travis-ci.org/RexOps/Rex/builds/154982941#L297-L311) for this change. Can you update the PR, please?

Since it seems to be perltidy-only, feel free to just amend the commit and force push here again, and github should pick it up automatically (in other words, IMHO there's no need to add a second tidy-only commit).

**Comment by stiron** [comment]
ATM I am not at a computer where I can do that, but I will update the commit.

**Comment by stiron** [comment]
Fix'd!

**Comment by krimdomu** [comment]
@stiron thanks for the cleanup. I'm going to merge it.

**Pull request merged**
