### PR TITLE
Add append_or_amend_line function to File command

### PR DESCRIPTION
**Pull request by abeverley**
This adds a function very similar to append_if_no_such_line, but one that allows existing lines to be updated.

### CODE REVIEW

**Comment by krimdomu** [comment]
Hi,

thank you much for this patch. I'm going to merge it.

**Comment by ferki** [comment]
@abeverley: nice job :+1:

Just to be on the safe side, could you please help adding a couple of tests for the new function as well in a follow-up PR? Perhaps into `t/file.t`, where `append_if_no_such_line` tests are living currently :)

**Comment by abeverley** [comment]
No problem, will do. I'll aim to do it tomorrow.

**Comment by abeverley** [comment]
PRs #542 and #543 added. I actually found a bug when adding the tests ;-)

**Comment by ferki** [comment]
Great \o/

**Pull request merged**
