### PR TITLE
Update tab completion for bash

### PR DESCRIPTION
**Pull request by mestia**
This PR fixes the following issues:
 - remove shebang, since completions aren't executables
 - complete available -* options
 - also complete hosts provided by _hosts function, for example from `~/.ssh/config`
 - call `rex -Ty` every time to make completion work between different `Rexfiles`

## Checklist
- [x] git commit messages are [well-written](https://chris.beams.io/posts/git-commit) (hopefully :))

### CODE REVIEW

**Comment by ferki** [comment]
Oh, I've left out some housekeeping: ref #1289 ([comment](https://github.com/RexOps/Rex/issues/1289#issuecomment-643139128))

**Comment by mestia** [comment]
> It works great based on my local tests, thanks! +1

Great!

> 
> I could see a few nitpicks about whitespace and commit organization, but nothing critical, so it's good to merge.

I am always open for critic, so feel free to tell me what could be improved.

**Comment by ferki** [comment]
> I am always open for critic, so feel free to tell me what could be improved.

Well, if you insist :) Dumping my thoughts:

Re: whitespace: there's an unnecessary extra empty line, and a double-space - I'll add a follow-up commit to this PR before merge, no need to change anything.

Re: commit organization: the commit contains 4 distinct changes, which makes it harder for the reviewer to tell which part of the diff is related to which change (especially when more than one change affects the same line), and might be harder for the maintainer to see where a specific change was introduced (or roll back only one of the changes). The commit message and the PR description lists those, which is good, but it also could be 4 commits (one commit for each change) next time.

Again, these are more like nitpicks, and all-in-all the PR is good enough to accept :+1:

**Comment by mestia** [comment]
Ok, in general I agree and also like to commit often, but since in this case the changes are kind of trivial, I though it would be easier to have it as one change. Thanks for accepting the PR!

**Comment by ferki** [comment]
Alright, I also added changelog and mailmap entries as a follow-up, so now all important elements should be self-contained in the PR ^^

**Pull request merged**
