### PR TITLE
Catch another one way to enable service which was added in FreeBSD 10.

### PR DESCRIPTION
**Pull request by timp87**
Oh, god, give me strength...

### CODE REVIEW

**Comment by ferki** [comment]
@timp87: oh, man, keep them coming :) I consider "late-merging" this for 1.3.3 (soon™).

**Comment by ferki** [comment]
Merged to release-1.3.3 branch.

**Comment by timp87** [comment]
@ferki thanks a lot! what about master branch? ;)

**Comment by ferki** [comment]
@timp87: once the release is out, the release branch will be merged to master too (and this issue should be closed automatically).

**Pull request closed without merging**
