### PR TITLE
[WIP] resources and functions are now similar

### PR DESCRIPTION
**Pull request by krimdomu**
- Added Controller class
- Refactored resources so that resources and functions work similar
- resources now also can have multiple code and type checking

### CODE REVIEW

**Comment by krimdomu** [comment]
* removed controller class
* added multisub class to handle functions with same name distinguished by signature.
* migrate resource and functions to multisub

**Comment by ferki** [comment]
@krimdomu: the test suite currently fails due to untidy files in the `bin` directory.

**Comment by krimdomu** [comment]
@ferki yes, i know. the test suite would also fail if these file are tidy ;-)

**Comment by krimdomu** [comment]
this pull request is obsolete: see #1212

**Pull request closed without merging**
