### PR TITLE
check if symlink is also to the right location. - fix bug #591

### PR DESCRIPTION
**Pull request by krimdomu**

### CODE REVIEW

**Comment by ferki** [comment]
:+1:

**Comment by krimdomu** [comment]
i've just updated this pull request, to also fix the bug of unlink() to remove symlinks.

**Comment by krimdomu** [comment]
link to: #591

**Comment by krimdomu** [comment]
Hi @ferki 
if there are no arguments against it, i would merge this to master?

**Comment by ferki** [comment]
@krimdomu: I took the liberty to update the commit message before merging, but otherwise the patch left unchanged.

**Pull request closed without merging**
